project:
  type: site
  output-dir: docs

website:
  title: "BiG"
  image: img/favicon.png
  google-analytics: "G-TY9ZC8SV4C"
  page-footer:
    left: "\\@BiG 2018-2021"
    right: 
      - text: "Built with Quarto"
        href: https://quarto.org/
    center: 
      - text: "About"
        href: ./about.qmd
  navbar:
    background: primary 
    logo: img/biglogo.png
    title: false
    pinned: true
    right:
      - href: index.qmd
        text: Home
      - people.qmd
      - text: Research
        menu:
          - research.qmd
          - self-burrowing.qmd
          - communication.qmd 
          - scour.qmd
      - publication.qmd
      - teaching.qmd
      - outreach.qmd
      - resources.qmd
      - news.qmd
      - about.qmd
      - icon: github
        href: https://github.com/big/

bibliography: jtpubs.bib

format:
  html:
    theme: 
      - assets/big.scss
    css: assets/style.css
    highlight-style: github
    toc: true
    header-includes: |
      <link rel="icon" href="img/favicon.png">
execute:
  echo: false
  warning: false 
  message: false
