---
title: Teaching 
---


## CEE 452/598 Foundations
The objective of the course is to apply the concepts and principles of soil mechanics in designing geotechnical engineering structures, mainly including,

* shallow foundations
* deep foundations
* retaining wall structures

## CEE 550 Soil Behavior
This course provides the student with an in-depth understanding of the factors determining and controlling the engineering properties and behavior of soils under different conditions. Topics covered include:

* Part I: Physicochemical Properties of Soil 
  * [Formation, mineralogy, composition, structure, soil water, inter-particle forces, effective stress]{.text-muted}
* Part II: Engineering Behaviors of Soil
  * [ strength behavior, volume change behaviors, deformation, critical state soil mechanics, time effects on strength and deformation, transport phenomena]{.text-muted}

## CEE 494/598 Bio-inspired Design
The objectives of the course are:

*  To provide the student with an overall understanding of bio-inspired design: principles, philosophies, methodologies, and tools;
*  To introduce emerging civil engineering challenges regarding sustainability and resilience concerns;
*  To show case and discuss example bio-inspired solutions to address some challenges;
*  To guide students to complete a conceptual bio-inspired design to address a chosen civil engineering challenge.
